galaxy_info:
  author: Yogesh Raheja
  description: Test case to understand Roles for My Experience with Ansible by Yogesh Raheja
  company: your company (optional)

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
    - name: CentOS
      versions:
      - 7

dependencies: 
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
  - { role: "motd" }
